# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  schedule:
  # each fifteen day of month
  - cron: "0 0 15 * *"
  push:
  pull_request:
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 17, 21 ]

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.0.0

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent compile verify --file pom.xml

    - name: Set first matrix job environment variable
      id: set-first-job
      if: ${{ matrix.java-version == '8' }}
      run: echo "::set-output name=first_job::true"

    - name: Distribute build results
      if: steps.set-first-job.outputs.first_job == 'true'
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: jars
        path: "*/target/*.jar"

    - name: Test Report JDK ${{ matrix.java-version }}
      uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3 # v1
      if: (success() || failure()) && github.event_name != 'pull_request' && github.actor != 'dependabot[bot]'  # run this step even if previous step failed
      with:
        name: Tests Report JDK ${{ matrix.java-version }}
        path: "*/target/surefire-reports/*.xml"
        reporter: java-junit

    - name: Codecov
      uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1

